### ISSUE TITLE
"name" is required in disposition?

### ISSUE THREAD

**Issue by eight04** [hapijs/content#10]
I was trying to parse something like `attachment; filename=1542796243.jpg` to get the filename, but it throws because of missing `name` parameter.

Any suggestion?

**Comment by hueniverse** [comment]
The implementation follows the spec. If you find a standard reference that shows otherwise, let me know.

**Comment by eight04** [comment]
Now I'm using [content-disposition](https://www.npmjs.com/package/content-disposition) to parse `Content-Disposition` header.

For `Content-Type`, I use regexp `/^\s*([^\s;]+)/`. Not sure how safe it is.
