### ISSUE TITLE
not support parse attachment

### ISSUE THREAD

**Issue by bluelovers** [hapijs/content#26]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): 
* *is this issue currently blocking your project?* (yes/no):
* *is this issue affecting a production system?* (yes/no):

#### Context

* *node version*: 
* *module version with issue*: 
* *last module version without issue*: 
* *environment* (e.g. node, browser, native): 
* *used with* (e.g. hapi application, another framework, standalone, ...):
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

```js
import hc from '@hapi/content';

let ret = hc.disposition(`attachment; filename="%E5%B0%8F%E8%AA%AA%E5%90%8D%E5%AD%97.epub"; filename*=UTF-8''%E5%B0%8F%E8%AA%AA%E5%90%8D%E5%AD%97.epub`);

console.log(ret)
```

**Comment by Garfield550** [comment]
https://github.com/hapijs/content/blob/18e1c55a29de1c869e7586d1b3ed43f326c63a77/lib/index.js#L75

Not support `attachment`

<img width="610" alt="image" src="https://user-images.githubusercontent.com/3471836/130331453-8fab3918-9f60-4dae-97cb-3e760cb411de.png">

GitHub Octokit return `attachment; filename=name-repo-a849a73.zip`, but @hapi/content can not parse it.

**Comment by devinivy** [comment]
I realize it's not readily apparent, but `disposition()` is designed specifically to parse multipart form data payloads, which requires the disposition type be `form-data`.  In the spec referenced above it notes:
> Note: This document does not apply to Content-Disposition header
      fields appearing in payload bodies transmitted over HTTP, such as
      when using the media type "multipart/form-data" ([[RFC2388](https://datatracker.ietf.org/doc/html/rfc2388)]).

Here is where we use `Content.disposition()`— it's in pez, hapi's multipart parser: https://github.com/hapijs/pez/blob/0cf5f3031a453e7db91610c070206342e89964b0/lib/index.js#L292

If we decide to parse out the disposition type and allow other types, we would have to treat this like a breaking change and ensure pez only allows form-data.

**Comment by Garfield550** [comment]
@devinivy Thanks, maybe should note this in the readme.

I saw `works great on its own or with other frameworks` from the readme, no specific implementation specifications are mentioned, so I use this to parse `attachment`.

> content is part of the hapi ecosystem and was designed to work seamlessly with the hapi web framework and its other components (but works great on its own or with other frameworks).

**Comment by devinivy** [comment]
I can see how that could easily happen.  Do you think if we changed its subtitle from "HTTP Content-* headers parsing" to "HTTP Content-* request headers parsing" that it would have signaled this better?  If so, I would give a PR for that change a ✅.

**Comment by Garfield550** [comment]
> I can see how that could easily happen. Do you think if we changed its subtitle from "HTTP Content-* headers parsing" to "HTTP Content-* request headers parsing" that it would have signaled this better? If so, I would give a PR for that change a ✅.

Yes, I think so.

Cause this package is not a full functional http `Content-` parser.
